#!/bin/sh
separator="|"

getTime() {
  time=$(date '+󱑆 %H:%M')
  
  echo $time
}

getDate() {
  date=$(date '+%B %e, %A')

  echo $date
}

battery () {
  ~/.dotfiles/scripts/statusbar/battery
}

wifi () {
  ~/.dotfiles/scripts/statusbar/wifi
}


while true; do
  xsetroot -name " $(getDate) $separator $(wifi)  $(battery)  $(getTime) "
  sleep 20
done
