#!/bin/sh
separator="|"

getTime() {
  time=$(date '+󱑆 %H:%M')
  
  echo $time
}

getDate() {
  date=$(date '+%a %e, %b')

  echo $date
}

battery () {
  ~/.dotfiles/scripts/statusbar/battery
}

wifi () {
  ~/.dotfiles/scripts/statusbar/wifi
}


while true; do
  xsetroot -name " $(wifi)  $(battery)  $(getDate) $(getTime) "
  sleep 20
done
