#!/bin/sh
separator="|"
time=$(date '+󱑆 %H:%M')
date=$(date '+%B %e, %A')

battery () {
  ~/.dotfiles/scripts/statusbar/battery
}

wifi () {
  ~/.dotfiles/scripts/statusbar/wifi
}


while true; do
  xsetroot -name " $date $separator $(wifi)  $(battery)  $time "
  sleep 1m
done
