#!/bin/sh
#if [ $(nmcli general | awk '{print 1}' | tail -n 1) = "disconnected" ]; then
#  echo 󰖪
#else
#  echo 󰖩
#fi
if [ $(cat /sys/class/net/wls1/operstate) = "up" ]; then
  echo 󰖩
else
  echo 󰖪
fi



