#!/bin/sh

directory=$(find $HOME/code -type d -not -wholename "*.git*" -a -not -wholename "*node_modules*" -a -not -wholename "*target*" -a -not -wholename "*debug*" | dmenu -i -l 10 -p "code")

if [ ! -z $directory ]
then
  cd $directory 
  st
fi
